name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
      # run prettier
    - name: Prettier Action
      uses: creyD/prettier_action@v3.0
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write .

      # run super linter
    #- name: Super-Linter
    #  uses: docker://github/super-linter:latest
      
      
